version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: skill-pathways-local
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
